name: Docker Image CI

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag rafaeloliveirax/apache-php8.4-fpm:latest

            - name: Log in to Docker Hub
              env:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}
              run: docker login -u $username -p $password

            - name: Push image to Docker Hub
              run: docker push rafaeloliveirax/apache-php8.4-fpm:latest
